# KERAS : Deep Learning Library
Keras is one of the major subfield of ML framework.

ML is nothiing but the study of algorithms similar to human brain.

Deep Learning is used in a variety of data scince fields like robotics, AI ,audio and video recognition and image recognition.

Artificial Neural Network (ANN) is the heart of many ML methodologies.

Keras is one of the most powerful python library and is builton top of deep learning libraries like TensorFlow and Theano for creating deep learning models.

Keras runs on top of open source machine libraries like TensorFlow, Theano and Cognitive toolkit (CNTK).

Theano is a numerical library used for fast numerical computation task.

TensorFlow is the symbolic math library which is used to create neural networks and deep learning models.

CNTK (Cognitive toolkit) is a deep learning framework developed by microsoft.

Theano and TensorFlow are powerful libraries but they are difficult to understand for creating neural networks.

Keras is a high level API built on the top of TensorFlow.


# Keras- Feature and Benefits
It provides a consistant, simple and extensible API.

They supportminimal structure and we can achieve the desired results.

It can run on varity of platforms(i.e, it supports multiple platforms).

It is user freindly framework and it runs on the top of both CPU and GPU (Generak Processing Unit).

It provides a large community support.

Keras neural networks are written in python which is easier to understand.

Keras supports both convolutional and recurrent neural networks.

Deep learning models are separate components and we can combine them in many ways.


# Keras - Layers
Keras layers are the main buildings block of Keras model.

Each layer receives the input data, performs some computation and finally output the tranformed information.

The output of the one layer will follow to the next layer as input.

# Layers Introduction :
A keras layer requires the shape of the input( input shape).

Input shape is required to understand the structure of input data.

Initializer is required to set the weight of each input.

Activators are required to transform the output to make it non-linear.

Constraints restricts and specify the range in which the weight of input data is to be generated

Regularizer will try to optimize the layer.

It applies penalties dynamically on the weights during the optimization process.

Keras requires the following details to create a complete layer:

                                                 1) shape of the input data.
                                                 2) Number of neurons/inputs in the layer.
                                                 3) Initializers.
                                                 4) Regularizers.
                                                 5) Constraints.
                                                 6) Activators.
                                                 
A simple keras layer is constructed using the sequential model API.It shows how keyras model and layers works.



In [1]:
pip install Keras

Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.



In [3]:
# Example
from keras.models import Sequential
from keras.layers import Activation, Dense
from keras import initializers
from keras import regularizers
from keras import constraints
import tensorflow

model=Sequential()                            # creates new model using sequential API
model.add(Dense(32,input_shape=(16,),kernel_initializer ='he_uniform',kernel_regularizer=None,kernel_constraint='MaxNorm',activation='relu'))
                                     # creates a new dense layer and add it into the model
                                     # it accepts the number of neurons (32) as its required parameter

                               # Dense is the beginning layer(or entry level layer) provided by keras
                                            # If the layer is the first layer, then we need to provide the input shape as well.
                                           
model.add(Dense(16,activation='relu'))       # creates the second dense layer with 16 units ans set relu as the activation function
model.add(Dense(8))                          # creates final dense layer with 8 units
 
# Kernel_regularizer : it represents the regularizer to be used.            None is set as the value
# Kernel_constraint : represents the constraints to be used
# MaxNorm : function is set as the value
# Activation : represents the activation to be used.
# Relu function is set as the value



In [16]:
import numpy as np
shape=(4,2)           # 3 rows & 2 columns 
input=np.zeros(shape)
print(input)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [15]:
import numpy as np
shape=(3,4,2)                # 3 marices with 4 rows & 2 columns
input=np.zeros(shape)
print(input)

[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]


In [24]:
# Initializers - Zeros
from keras.models import Sequential
from keras.layers import Activation, Dense
from keras import initializers

my_init=initializers.Zeros()
model=Sequential()
model.add(Dense(512,activation='relu',input_shape=(784,),kernel_initializer=my_init))

In [22]:
# Initializers - Ones
from keras.models import Sequential
from keras.layers import Activation, Dense
from keras import initializers

my_init=initializers.Ones()
model=Sequential()
model.add(Dense(512,activation='relu',input_shape=(784,),kernel_initializer=my_init))

In [26]:
# Initializers - Constant
# generates a constant value specified by the user for all input data. value is nothingbut the input data.
from keras.models import Sequential
from keras.layers import Activation, Dense
from keras import initializers

my_init=initializers.Constant(value=0)
model.add(Dense(512,activation='relu',input_shape=(784,),kernel_initializer=my_init))

In [32]:
# Initializers - Random Uniform 
# It generates values using uniform distribution of the input data

from keras import initializers
my_init=initializers.RandomUniform(minval=-0.05,maxval=0.05,seed=None)
         # minival: lower bound of the random values to generate
         # maxval : upper bound of the values to generate
model.add(Dense(512,activation='relu',input_shape=(784,),kernel_initializer=my_init))

In [33]:
# Initializers - Random Normal
# generates value using truncated normal distribution of input data.
from keras.models import Sequential
from keras.layers import Activation, Dense
from keras import initializers

my_init=initializers.RandomNormal(mean=0.0,stddev=0.05,seed=None)
model.add(Dense(512,activation='relu',input_shape=(784,),kernel_initializer=my_init))

In [35]:
# Initializers - Truncated Normal
# generates value using truncated normal distribution of input data.
from keras.models import Sequential
from keras.layers import Activation, Dense
from keras import initializers

my_init=initializers.TruncatedNormal(mean=0.0,stddev=0.05,seed=None)
model.add(Dense(512,activation='relu',input_shape=(784,),kernel_initializer=my_init))

In [37]:
# Initializers - Glorot Normal
# generates value using glorot normal distribution of input data.
from keras.models import Sequential
from keras.layers import Activation, Dense
from keras import initializers

my_init=initializers.glorot_normal(seed=None)
model.add(Dense(512,activation='relu',input_shape=(784,),kernel_initializer=my_init))

In [38]:
# Initializers - he_normal

from keras.models import Sequential
from keras.layers import Activation, Dense
from keras import initializers

my_init=initializers.he_normal(seed=None)
model.add(Dense(512,activation='relu',input_shape=(784,),kernel_initializer=my_init))

In [39]:
# Initializers - Orthogonal
from keras.models import Sequential
from keras.layers import Activation, Dense
from keras import initializers

my_init=initializers.Orthogonal(gain=1.0,seed=None)
model.add(Dense(512,activation='relu',input_shape=(784,),kernel_initializer=my_init))

In [40]:
# Initializers - Identity
from keras.models import Sequential
from keras.layers import Activation, Dense
from keras import initializers

my_init=initializers.Identity(gain=1.0)
model.add(Dense(512,activation='relu',input_shape=(784,),kernel_initializer=my_init))

In [70]:
#                                            Constraints Initializers - UnitNorm
from keras.models import Sequential
from keras.layers import Activation, Dense
from keras import constraints

my_constrain=constraints.UnitNorm(axis=0)
model=Sequential()
model.add(Dense(512,activation='relu',input_shape=(784,),kernel_initializer=my_init))

In [47]:
# Constraints Initializers - MaxNorm
from keras.models import Sequential
from keras.layers import Activation, Dense
from keras import constraints

my_constrain=constraints.MaxNorm(max_value=2,axis=0)
model=Sequential()
model.add(Dense(512,activation='relu',input_shape=(784,),kernel_initializer=my_init))

In [49]:
# Constraints Initializers - MinMaxNorm
from keras.models import Sequential
from keras.layers import Activation, Dense
from keras import constraints

my_constrain=constraints.MinMaxNorm(min_value=0.0,max_value=1,rate=1.0,axis=0)
model=Sequential()
model.add(Dense(512,activation='relu',input_shape=(784,),kernel_initializer=my_init))

In [50]:
#                                          Regularizers Initializers - l1
from keras.models import Sequential
from keras.layers import Activation, Dense
from keras import regularizers

my_regularizer=regularizers.l1(0.)
model=Sequential()
model.add(Dense(512,activation='relu',input_shape=(784,),kernel_initializer=my_init))

In [66]:
# Regularizers Initializers - l2
from keras.models import Sequential
from keras.layers import Activation, Dense
from keras import regularizers

my_regularizer=regularizers.l2(0.)
model=Sequential()
model.add(Dense(512,activation='relu',input_shape=(784,),kernel_initializer=my_init))

In [69]:
# Regularizers Initializers - L1L2
from keras.models import Sequential
from keras.layers import Activation, Dense
from keras import regularizers

my_regularizer=regularizers.L1L2(0.)
model=Sequential()
model.add(Dense(512,activation='relu',input_shape=(784,),kernel_initializer=my_init))

In [55]:
#                                      Initializers - Activation - linear
from keras.models import Sequential


model=Sequential()
model.add(Dense(512,activation='linear',input_shape=(784,)))

In [56]:
# Initializers - Activation - elu
from keras.models import Sequential


model=Sequential()
model.add(Dense(512,activation='elu',input_shape=(784,)))

In [58]:
# Initializers - Activation - softmax
from keras.models import Sequential


model=Sequential()
model.add(Dense(512,activation='softmax',input_shape=(784,)))

In [59]:
# Initializers - Activation - softplus
from keras.models import Sequential


model=Sequential()
model.add(Dense(512,activation='softplus',input_shape=(784,)))

In [60]:
# Initializers - Activation - softsign
from keras.models import Sequential


model=Sequential()
model.add(Dense(512,activation='softsign',input_shape=(784,)))

In [61]:
# Initializers - Activation - sigmoid
from keras.models import Sequential


model=Sequential()
model.add(Dense(512,activation='sigmoid',input_shape=(784,)))

In [62]:
# Initializers - Activation - hard_signmoid
from keras.models import Sequential


model=Sequential()
model.add(Dense(512,activation='hard_sigmoid',input_shape=(784,)))

In [63]:
# Initializers - Activation - exponential
from keras.models import Sequential


model=Sequential()
model.add(Dense(512,activation='exponential',input_shape=(784,)))

In [64]:
#                                    Variance Scaling Initializer
# generates value based on the input shape and output shape of the layer along with the specified scale

from keras.models import Sequential
from keras.layers import Activation, Dense
from keras import initializers

my_init=initializers.VarianceScaling(scale=1.0,mode='fan_in',distribution='normal',seed=None)
                     # scale : denotes scaling factor
                     # model : represent any one of the fan_in, fan_out and fan_avg values.
                     # distribution : represents either normal or uniform distribution
model.add(Dense(512,activation='relu',input_shape=(784,),kernel_initializer=my_init))

# it find the stddev value for normal disributionn using below formula
### and then find the weights using normal distribution

# Stddev=sqrt(scale/n)       where n represents no. of inputs for mode= fan_in
                             # where n represents no. of out units for mode= fan_out
                             # OR avg no. of inputs and outputs units for mode = fan_avg
        
# It find the limit of uniform distribution using below formula and then find the weights using normal distribution
# limit=sqrt(3*scale/n)