In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [3]:
# more than one dimensional 

In [4]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [5]:
a=np.array([1,2,3,4],ndmin=2)
a

array([[1, 2, 3, 4]])

In [6]:
a=np.array([1,2,3,4],dtype=complex)          # complex data
a

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [7]:
dt=np.dtype(np.int32)
print(dt)

int32


In [8]:
# Ndarray.shape : it returns a tupple containing array dimensions. Used to resize array.
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [9]:
a=np.array([[1,2,3],[4,5,6]])
a.shape=(3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [10]:
a=np.arange(24) # till : n-1
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [11]:
a.ndim                    # reshape array 
b=a.reshape(3,2,4)        # 3 arrays 2 rows and 4 columns
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [12]:
# Numpy.itemsize: returns length of each element of array in bytes.

In [13]:
#dtype of array is int8(1 byte)
x=np.array([1,2,3,4,5],dtype=np.int8)
print(x.itemsize)

1


In [14]:
# Numpy.Flags
# C_CONTOGUOUS(C): DATA IS IN SINGLE , C-STYLE CONTIGUOUS SEGMENT.
# F_CONTIGUOUS(F): DATA IS IN SINGLE , FORTAN-STYLE CONTIGUOUS SEGMENT.
# OWNDATA(O): ARRAY OWNS THE MEMORY IT  USES OR BORROWS IT FROM ANOTHER OBJECT.
# WRITEABLE(W): DATA AREA CAN BE WRITTEN TO. SETTING THIS TO FALSE LOCKS THE DATA,MAKING IT READ-ONLY.
# ALIGNED(A): DATA ABD ALL ELEMENTS ARE ALIGNED APPROPRIATELY FOR THE HARDWARE.
# UPDATEIFCOPY(U) : ARRAY IS COPY OF SOME OTHER ARRAY.WHEN THIS ARRAY IS DEALLOCATED, THE BASE ARRAY WILL BE UPDATED WITH THE CONTENTS OF THIS ARRAY.

In [15]:
## Numpy.zeroes: it returns a new array of specified size, filled with zeroes.
# numpy.zeroes(shape,dtype=float,order='C') ->> # shape of an empty array in int
                                                # dtype : desired output datatype.
                                                # order=C for C-style row major aray.

In [16]:
## Numpy- array from existing array
# Numpy.asarray: it is used for coverting python sequence into an n-dimensional array
# Numpy.asarray(a,dtype=Nine,order=None)   ->> # a- input in any form such as list orlist of tuples.
                                               # dtype: by default, the datatype of the input data is applied to the resultant array.
                                               # order - C Row Major

In [17]:
# convert list to ndarray
x=[1,2,3]
a=np.asarray(x)
print(a)

[1 2 3]


In [18]:
s=(1,2,2)
h=np.array(s)
print(h)

[1 2 2]


In [19]:
# Numpy: indexing and slicing
                        # contents of ndarrav objevt can be accessed by indexumg or slicing.

In [20]:
a=np.arange(10)
s=slice(2,7,2)
print(a[s])

[2 4 6]


In [21]:
x=np.arange(10)
b=a[2:7:2]
print(b)

[2 4 6]


In [22]:
#array to begin with
x=np.array([[1,2,3],[3,4,5],[4,5,6]])
print("Our array is :")
print(x)
print("\n") # this returns array of items in the second coloumn
print("The items in the second column are:")
print(x[...,1])
print("\n")
# Now we will slice all items from the second row
print("The items in the second row are:")
print(x[1,...])
print("\n")
# Now we will slice all items from column 1 onwards
print("the items column 1 onwards are :")
print(x[...,1:])


Our array is :
[[1 2 3]
 [3 4 5]
 [4 5 6]]


The items in the second column are:
[2 4 5]


The items in the second row are:
[3 4 5]


the items column 1 onwards are :
[[2 3]
 [4 5]
 [5 6]]


In [23]:
## Numpy- Iterating over an array.
                       # it contains an iterator object 'nditer'
                       # it is a multidimensional array object which is used to iterate over an array
                       # each element of an array is accessed using the python standard iterator interface.

In [24]:
s=np.arange(0,60,5)
s=s.reshape(3,4)
print("Original array is: ")
print(s)
print("\n")
print("Modified array is :")
for x in np.nditer(s):
    print(x)

Original array is: 
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Modified array is :
0
5
10
15
20
25
30
35
40
45
50
55
